#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wclean all consistentSolvers

# FSI
wclean fsi/bodyMotionFoam
wclean fsi/pimpleBodyFsiFoam
wclean fsi/pimpleRigidBodyFsiFoam
wclean fsi/simpleBodyFsiFoam

# Gusts
#wclean gust/pimpleBodyGustFoamRC
#wclean gust/pimpleGustFoam

# Coupled
wclean coupled/pUCoupledFoam
wclean coupled/unsteadyPUCoupledFoam

# Remaining solver
wclean movingMesh/moveBodyFoam
wclean movingMesh/myMoveDynamicMesh
wclean simpleFoamChannel
wclean simpleSRFAbsFoam
