#!/bin/bash

# Merge stderr to stdout (optional, otherwise they're in separate files)
#PBS -j oe

# Specify the output filename explicitly (optional; the default is named
# from the job ID, in the directory where qsub was run.)
#PBS -o ./qsub.log

# Well, here you can specify the name of your job
#PBS -N moving4

# Request a job on 1 nodes, with 1 processors per node.
#PBS -l nodes=1:ppn=4:typef,walltime=18:00:00

echo Job started on `uname -n` at `date`

cd $PBS_O_WORKDIR
. ~/foam/foam-extend-3.1/etc/bashrc
# source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#run
buildAndRun_timeOrder > buildAndRun_timeOrder.log 2>&1
