#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake pimpleNoBodyFoamCiCrotExp
wmake DGCLpimpleBodyFoamBDF3
wmake pimpleBodyFsiFoamBDF3
wmake pimpleBodyFoamBDF3
wmake inverseMatrixTesting
