#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wclean pimpleNoBodyFoamCiCrotExp
wclean DGCLpimpleBodyFoamBDF3
wclean pimpleBodyFsiFoamBDF3
wclean pimpleBodyFoamBDF3
wclean inverseMatrixTesting
