#!/bin/sh
#make sure to run from this dir
cd ${0%/*} || exit 1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="pimpleNoBodyFoamCiCrotExp_uf"

cellSet
runApplication $application
writeSets
