#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake libso mySchemes
wmake libso myBoundaries
wmake libso RBFmeshInterpolation
wmake libso gusts
wmake libso bodyMotion
wmake libso rigidBody
wmake libso fsi
wmake libso mySolidBodyMotion
wmake libso myTurbulenceModels
wmake libso SRFModelAbs
